require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TimedaysController do

  # This should return the minimal set of attributes required to create a valid
  # Timeday. As you add validations to Timeday, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "day" => "2014-02-14" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimedaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all timedays as @timedays" do
      timeday = Timeday.create! valid_attributes
      get :index, {}, valid_session
      assigns(:timedays).should eq([timeday])
    end
  end

  describe "GET show" do
    it "assigns the requested timeday as @timeday" do
      timeday = Timeday.create! valid_attributes
      get :show, {:id => timeday.to_param}, valid_session
      assigns(:timeday).should eq(timeday)
    end
  end

  describe "GET new" do
    it "assigns a new timeday as @timeday" do
      get :new, {}, valid_session
      assigns(:timeday).should be_a_new(Timeday)
    end
  end

  describe "GET edit" do
    it "assigns the requested timeday as @timeday" do
      timeday = Timeday.create! valid_attributes
      get :edit, {:id => timeday.to_param}, valid_session
      assigns(:timeday).should eq(timeday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Timeday" do
        expect {
          post :create, {:timeday => valid_attributes}, valid_session
        }.to change(Timeday, :count).by(1)
      end

      it "assigns a newly created timeday as @timeday" do
        post :create, {:timeday => valid_attributes}, valid_session
        assigns(:timeday).should be_a(Timeday)
        assigns(:timeday).should be_persisted
      end

      it "redirects to the created timeday" do
        post :create, {:timeday => valid_attributes}, valid_session
        response.should redirect_to(Timeday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved timeday as @timeday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timeday.any_instance.stub(:save).and_return(false)
        post :create, {:timeday => { "day" => "invalid value" }}, valid_session
        assigns(:timeday).should be_a_new(Timeday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timeday.any_instance.stub(:save).and_return(false)
        post :create, {:timeday => { "day" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested timeday" do
        timeday = Timeday.create! valid_attributes
        # Assuming there are no other timedays in the database, this
        # specifies that the Timeday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Timeday.any_instance.should_receive(:update).with({ "day" => "2014-02-14" })
        put :update, {:id => timeday.to_param, :timeday => { "day" => "2014-02-14" }}, valid_session
      end

      it "assigns the requested timeday as @timeday" do
        timeday = Timeday.create! valid_attributes
        put :update, {:id => timeday.to_param, :timeday => valid_attributes}, valid_session
        assigns(:timeday).should eq(timeday)
      end

      it "redirects to the timeday" do
        timeday = Timeday.create! valid_attributes
        put :update, {:id => timeday.to_param, :timeday => valid_attributes}, valid_session
        response.should redirect_to(timeday)
      end
    end

    describe "with invalid params" do
      it "assigns the timeday as @timeday" do
        timeday = Timeday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timeday.any_instance.stub(:save).and_return(false)
        put :update, {:id => timeday.to_param, :timeday => { "day" => "invalid value" }}, valid_session
        assigns(:timeday).should eq(timeday)
      end

      it "re-renders the 'edit' template" do
        timeday = Timeday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timeday.any_instance.stub(:save).and_return(false)
        put :update, {:id => timeday.to_param, :timeday => { "day" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested timeday" do
      timeday = Timeday.create! valid_attributes
      expect {
        delete :destroy, {:id => timeday.to_param}, valid_session
      }.to change(Timeday, :count).by(-1)
    end

    it "redirects to the timedays list" do
      timeday = Timeday.create! valid_attributes
      delete :destroy, {:id => timeday.to_param}, valid_session
      response.should redirect_to(timedays_url)
    end
  end

end
