require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TimecodesController do

  # This should return the minimal set of attributes required to create a valid
  # Timecode. As you add validations to Timecode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "descr" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimecodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all timecodes as @timecodes" do
      timecode = Timecode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:timecodes).should eq([timecode])
    end
  end

  describe "GET show" do
    it "assigns the requested timecode as @timecode" do
      timecode = Timecode.create! valid_attributes
      get :show, {:id => timecode.to_param}, valid_session
      assigns(:timecode).should eq(timecode)
    end
  end

  describe "GET new" do
    it "assigns a new timecode as @timecode" do
      get :new, {}, valid_session
      assigns(:timecode).should be_a_new(Timecode)
    end
  end

  describe "GET edit" do
    it "assigns the requested timecode as @timecode" do
      timecode = Timecode.create! valid_attributes
      get :edit, {:id => timecode.to_param}, valid_session
      assigns(:timecode).should eq(timecode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Timecode" do
        expect {
          post :create, {:timecode => valid_attributes}, valid_session
        }.to change(Timecode, :count).by(1)
      end

      it "assigns a newly created timecode as @timecode" do
        post :create, {:timecode => valid_attributes}, valid_session
        assigns(:timecode).should be_a(Timecode)
        assigns(:timecode).should be_persisted
      end

      it "redirects to the created timecode" do
        post :create, {:timecode => valid_attributes}, valid_session
        response.should redirect_to(Timecode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved timecode as @timecode" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timecode.any_instance.stub(:save).and_return(false)
        post :create, {:timecode => { "descr" => "invalid value" }}, valid_session
        assigns(:timecode).should be_a_new(Timecode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timecode.any_instance.stub(:save).and_return(false)
        post :create, {:timecode => { "descr" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested timecode" do
        timecode = Timecode.create! valid_attributes
        # Assuming there are no other timecodes in the database, this
        # specifies that the Timecode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Timecode.any_instance.should_receive(:update).with({ "descr" => "MyString" })
        put :update, {:id => timecode.to_param, :timecode => { "descr" => "MyString" }}, valid_session
      end

      it "assigns the requested timecode as @timecode" do
        timecode = Timecode.create! valid_attributes
        put :update, {:id => timecode.to_param, :timecode => valid_attributes}, valid_session
        assigns(:timecode).should eq(timecode)
      end

      it "redirects to the timecode" do
        timecode = Timecode.create! valid_attributes
        put :update, {:id => timecode.to_param, :timecode => valid_attributes}, valid_session
        response.should redirect_to(timecode)
      end
    end

    describe "with invalid params" do
      it "assigns the timecode as @timecode" do
        timecode = Timecode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timecode.any_instance.stub(:save).and_return(false)
        put :update, {:id => timecode.to_param, :timecode => { "descr" => "invalid value" }}, valid_session
        assigns(:timecode).should eq(timecode)
      end

      it "re-renders the 'edit' template" do
        timecode = Timecode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timecode.any_instance.stub(:save).and_return(false)
        put :update, {:id => timecode.to_param, :timecode => { "descr" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested timecode" do
      timecode = Timecode.create! valid_attributes
      expect {
        delete :destroy, {:id => timecode.to_param}, valid_session
      }.to change(Timecode, :count).by(-1)
    end

    it "redirects to the timecodes list" do
      timecode = Timecode.create! valid_attributes
      delete :destroy, {:id => timecode.to_param}, valid_session
      response.should redirect_to(timecodes_url)
    end
  end

end
